### ISSUE TITLE
Inquiry about Open Sourcing Code and Pseudo-code for BMA Implementation

### ISSUE THREAD

**Issue by FrankZhangRp** [thuml/CLIPood#1]
@longmingsheng @GXZlegend 
Hello,

I am writing to inquire about the open-sourcing of the code. I am interested in learning more about the implementation of BMA and would like to know if there are any plans to open-source the code in the near future.

Additionally, I was wondering if it would be possible for you to provide a pseudo-code or high-level description of the implementation of BMA. I understand that the specifics of the implementation may be proprietary, but any information you could provide would be greatly appreciated.

Thank you for your time, and I look forward to hearing from you soon.

**Comment by GXZlegend** [comment]
Thanks for your interest in our paper! We have already uploaded our code. For BMA, please refer to `GeneralMovingAverage` in `engine.py` and `main` in `main.py` for details.
