### ISSUE TITLE
Could you please explain the implementation of MMS?

### ISSUE THREAD

**Issue by yuxi120407** [thuml/CLIPood#4]
Hi Dear Authors:

Thank you so much for your codes for the paper.
I have a question for the implementation codes of MMS.

```
# compute output
        f = model(x)
        f = f / f.norm(dim=-1, keepdim=True)
        f -= args.alpha * text_features[labels]
        y = f @ text_features.T
        y = args.temperature * y

        loss = F.cross_entropy(y, labels)
```

Could you please  explain it and what's the alpha here, or should it be lambda?
Many thanks in advance.

**Comment by GXZlegend** [comment]
Apologize for this typo. `args.alpha` should be `args.lambda` here.
