### ISSUE TITLE
requirements.txt file is not found

### ISSUE THREAD

**Issue by saraalemadi** [thuml/CLIPood#6]
Hi,

I am interested in replicating your experiments but I can't find the requirements.txt file. Therefore, could you kindly upload it.

Thanks.
Sara

**Comment by GXZlegend** [comment]
Thanks. We recognize that we provided a wrong version of README.md. The correct steps for getting started have been updated.

**Comment by saraalemadi** [comment]
Thanks @GXZlegend!

**Comment by saraalemadi** [comment]
Thanks @GXZlegend!
